### ISSUE TITLE
Feedback Sprint 2

### ISSUE THREAD

**Issue by MarciaMillanao** [ElizabethVegaM/scl-2018-05-bc-core-am-datadashboard#5]
Hola chicas!
Estuve revisando el avance que llevan y tengo algunos comentarios:

1.- Les recomiendo usar nombre de identificadores (variables en js, clases o id en html & css) bien descriptivos y en inglés.

2.- Utilicen todo el HTML semántico (vi que usaron nav, header y section), con eso me refiero a las etiquetas `<header></header> <section></section> <article></article> <aside></aside> <nav></nav> <footer></footer>`.

3.- Usen los issues para coordinarse y comunicarse entre ustedes.

4.- Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía [https://www.youtube.com/watch?v=9SZSHGA95x4](url)
[https://www.youtube.com/watch?v=nI5VdsVl0FM](url) .

5.- Revisar script de bootstrap en HTML, no estén duplicados.

Vamos con todo!!!

**Comment by ElizabethVegaM** [comment]
Gracias Marcia, lo revisaremos!

**Comment by abejapower** [comment]
gracias marcia , entonces los comentarios lo hacemos como isues o comentarios y issues?
